version: '3'

services:
  reverse-proxy:
    image: traefik:v2.1
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

    ports:
      - "80:80"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    image: ghcr.io/80-20-mp/backend:main

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.backend.loadbalancer.server.port=80"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.middlewares.api-strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=api-strip-prefix@docker"

  frontend:
    image: ghcr.io/80-20-mp/frontend:main

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
